name: Publish DataConnector to GitHub Packages

on:
  push:
    branches:
      - main
    paths:
      - "DataConnector/**"
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          source-url: https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
        env:
          NUGET_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Authenticate with GitHub Packages
        run: |
          if ! dotnet nuget list source | grep -q "github"; then
            dotnet nuget add source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --name github --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text
          else
            echo "NuGet source 'github' already exists. Skipping addition."
          fi

      - name: Restore Dependencies
        run: dotnet restore DataConnector/DataConnector.csproj

      - name: Build & Pack DataConnector
        run: dotnet pack DataConnector/DataConnector.csproj --configuration Release --output ./packages

      - name: Publish to GitHub Packages
        run: dotnet nuget push ./packages/*.nupkg --source github --api-key ${{ secrets.GITHUB_TOKEN }} --skip-duplicate